version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: docengine_db
    restart: always
    environment:
      # Docker usará los valores definidos en el archivo .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-broker:
    image: redis:alpine
    container_name: docengine_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data: